<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="mecanum_robot">
    <!-- 2D激光雷达支架 -->
    <link name="laser_support_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${support_radius}" length="${support_height}"/>
            </geometry>
            <material name="grey">
                <color rgba="0.5 0.5 0.5 1.0"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${support_radius}" length="${support_height}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="0.1"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.00001"/>
        </inertial>
    </link>
    <joint name="laser_support_joint" type="fixed">
        <parent link="base_link"/>
        <child link="laser_support_link"/>
        <origin xyz="0 0 ${base_height/2 + support_height/2}" rpy="0 0 0"/>
    </joint>
    <gazebo reference="laser_support_link">
        <material>Gazebo/Grey</material>
    </gazebo>
    <!-- 2D激光雷达 -->
    <link name="laser_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${laser_radius}" length="${laser_height}"/>
            </geometry>
            <material name="black">
                <color rgba="0.1 0.1 0.1 1.0"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${laser_radius}" length="${laser_height}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="0.2"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
        </inertial>
    </link>
    <joint name="laser_joint" type="fixed">
        <parent link="laser_support_link"/>
        <child link="laser_link"/>
        <origin xyz="0 0 ${support_height/2 + laser_height/2}" rpy="0 0 0"/>
    </joint>
    <!-- 激光雷达 Gazebo 插件 -->
   <gazebo reference="laser_link">
    <material>Gazebo/Green</material>
    <sensor type="ray" name="rplidar"> 
        <pose>0 0 0 0 0 0</pose>
        <visualize>false</visualize>
        <update_rate>6</update_rate>
        <ray>
            <scan>
                <horizontal>
                    <samples>360</samples>
                    <resolution>1</resolution>
                    <min_angle>-3.1415926</min_angle>
                    <max_angle>3.1415926</max_angle>
                </horizontal>
            </scan>
            <range>
                <min>0.15</min>
                <max>10</max>
                <resolution>0.01</resolution>
            </range>
            <noise>
                <type>gaussian</type>
                <mean>0.0</mean>
                <stddev>0.01</stddev>
            </noise>
        </ray>
        <plugin name="gazebo_ros_rplidar_controller" filename="libgazebo_ros_laser.so">  
            <topicName>scan</topicName>
            <frameName>laser_link</frameName>
        </plugin>
    </sensor>
</gazebo>
</robot>